# Generated by Django 3.2.5 on 2021-08-20 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='requestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('Author', models.CharField(max_length=50)),
                ('booktitle', models.CharField(max_length=50)),
                ('Genre', models.CharField(max_length=50)),
                ('anyother', models.CharField(max_length=50)),
                ('information', models.TextField()),
            ],
        ),
    ]
