# Generated by Django 3.2.5 on 2021-08-21 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestform',
            name='anyother',
        ),
    ]
