# Generated by Django 3.2.5 on 2021-08-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/NewBook')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('bookgenre', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='New_books.bookgenre')),
            ],
        ),
    ]
