# Generated by Django 3.2.5 on 2021-08-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newbook',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
